set -g prefix C-x
# Allows for faster key repetition
set -s escape-time 0

# # default statusbar colors
set -g status-bg blue
set -g status-fg white
set -g status-left "#P"
set -g status-right "#[fg=green]%R"
set -g status-attr default

# # command/message line colors
set-option -g message-fg white
set-option -g message-bg black
set-option -g message-attr bright

set-option -g pane-active-border-fg blue
