set -g prefix C-x

bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Allows for faster key repetition
set -s escape-time 0

# # default statusbar colors
set -g status-bg blue
set -g status-fg white
set -g status-left "#P"
set -g status-right "#[fg=green]%R"
#set -g status-attr default
#
## # command/message line colors
#set-option -g message-fg white
#set-option -g message-bg black
#set-option -g message-attr bright
#
#set-option -g pane-active-border-fg blue
#
#/home/rob/.tmux.conf:10: invalid option: status-attr                                                                                                       [0/0]
#/home/rob/.tmux.conf:13: invalid option: message-fg
#/home/rob/.tmux.conf:14: invalid option: message-bg
#/home/rob/.tmux.conf:15: invalid option: message-attr
#/home/rob/.tmux.conf:17: invalid option: pane-active-border-fg
#
