#!/bin/sh
# Generates .vim/CHEATSHEET.md: vim's default buffer/window/cursor/editing keys, plus the
# custom overrides actually defined in .vimrc (and any .vim/core, .vim/stacks modules that
# exist yet), read from the files themselves rather than hand-copied -- so the custom-map
# table can't silently drift from what .vimrc really binds.
#
# Run it by hand after changing a mapping: .vim/cheatsheet.sh
#
# POSIX sh, no deps beyond grep/sed/awk -- same rules as scripts/lib.sh callers, even
# though this script lives outside the install.d contract (it writes .vim/CHEATSHEET.md,
# a repo file, not $TARGET or $HOME).

set -eu

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO=$(cd "$SCRIPT_DIR/.." && pwd)
VIMRC="$REPO/.vimrc"
OUT="$REPO/.vim/CHEATSHEET.md"

# Every vimscript file that can define custom mappings, in load order. Globs that match
# nothing (.vim/core, .vim/stacks not built yet) are dropped rather than passed through
# literally, which is what the -f test is for.
MAP_SOURCES="$VIMRC"
for f in "$REPO"/.vim/core/*.vim "$REPO"/.vim/stacks/*/*.vim; do
  [ -f "$f" ] && MAP_SOURCES="$MAP_SOURCES $f"
done

# --- extract statically-written nnoremap/inoremap/vnoremap lines -----------------------
# Catches `nnoremap <C-a> <Home>`-style lines directly. Loop/execute-built mappings (the
# Alt-hjkl focus/resize table in .vimrc) don't match this shape -- vimscript string
# concatenation isn't worth parsing here -- so those are listed by hand in the "generated
# at runtime" section below, next to a note pointing at the loop that builds them.
extract_static() {
  grep -hEn '^(nnoremap|inoremap|vnoremap)(\s+<silent>)?\s+\S+\s+\S' $MAP_SOURCES 2>/dev/null \
    | grep -Ev "^\S*:\s*(nnoremap|inoremap|vnoremap)\s+<silent>" \
    || true
}

# Build one row per distinct LHS key, showing which of n/i/v it's bound in and the RHS
# (mode column collapses n+i+v into one row when the RHS is identical across all three,
# which is how every static mapping in .vimrc is actually written).
# Plain field-splitting rather than gawk's match(str, re, arr) -- that's a gawk extension,
# not POSIX, and macOS ships BSD awk with no gawk in its base install. One line in, one
# mode/key/rhs triple out.
static_table() {
  extract_static | sed -E 's/^[0-9]+:[[:space:]]*//' | awk '
    {
      mode = substr($1, 1, 1)
      i = 2
      if ($2 == "<silent>") i = 3
      key = $i
      rhs = ""
      for (j = i + 1; j <= NF; j++) rhs = rhs (j > i + 1 ? " " : "") $j
      order_key = key "\x1c" rhs
      if (!(order_key in seen)) { order[++n] = order_key; seen[order_key] = 1 }
      modes[order_key] = modes[order_key] mode
    }
    END {
      for (i = 1; i <= n; i++) {
        split(order[i], parts, "\x1c")
        key = parts[1]; rhs = parts[2]
        m = modes[order[i]]
        label = (index(m, "n") && index(m, "i") && index(m, "v")) ? "N/I/V" : \
                (index(m, "n") && index(m, "v")) ? "N/V" : \
                (index(m, "n") && index(m, "i")) ? "N/I" : \
                (index(m, "n")) ? "N" : (index(m, "i")) ? "I" : "V"
        printf "| `%s` | %s | `%s` |\n", key, label, rhs
      }
    }
  '
}

STATIC_ROWS=$(static_table)

cat > "$OUT" <<EOF
# vim cheatsheet

Generated by \`.vim/cheatsheet.sh\` from$([ "$MAP_SOURCES" != "$VIMRC" ] && echo " .vimrc and .vim/core, .vim/stacks" || echo " .vimrc"). Custom
mappings below are read out of the config, not hand-copied — re-run the script after
changing a mapping. Defaults tables are vim's own, unaffected by this repo's config.

Notation: \`<C-x>\` = Ctrl-x, \`<M-x>\` = Alt-x (Option on macOS), \`<S-x>\` = Shift-x.
\`N\`/\`I\`/\`V\` = Normal / Insert / Visual mode. See \`scripts/keyboard/CHEATSHEET.md\` for why
Alt is the in-terminal modifier and how it reaches vim at all.

## Custom overrides (from .vimrc)

| Key | Mode | Action |
| --- | ---- | ------ |
$STATIC_ROWS

### Generated at runtime (loop-built, not a literal \`nnoremap\` line)

.vimrc builds these from a table rather than writing one \`nnoremap\` per key, so they don't
show up in the grep above. Two tables: pane/split **focus** and **resize**, both shared
with tmux — at the edge of vim's splits the key hands off to \`tmux select-pane\` /
\`tmux resize-pane\` instead of doing nothing. See \`s:VimIdeFocus\`/\`s:VimIdeResize\` in
.vimrc and \`scripts/keyboard/CHEATSHEET.md\` for the full tmux+vim picture.

| Key | Mode | Action |
| --- | ---- | ------ |
| \`<M-h>\` / \`<M-Left>\`  | N/I/V | focus split left (else tmux pane left) |
| \`<M-j>\` / \`<M-Down>\`  | N/I/V | focus split down (else tmux pane down) |
| \`<M-k>\` / \`<M-Up>\`    | N/I/V | focus split up (else tmux pane up) |
| \`<M-l>\` / \`<M-Right>\` | N/I/V | focus split right (else tmux pane right) |
| \`<M-H>\` / \`<M-S-Left>\`  | N/I/V | narrow split (else tmux pane) |
| \`<M-J>\` / \`<M-S-Down>\`  | N/I/V | lengthen split (else tmux pane) |
| \`<M-K>\` / \`<M-S-Up>\`    | N/I/V | shorten split (else tmux pane) |
| \`<M-L>\` / \`<M-S-Right>\` | N/I/V | widen split (else tmux pane) |

### Other custom behavior (not a keymap)

| Trigger | Mode | Action |
| ------- | ---- | ------ |
| \`y\` (any yank) | N/V | also copies to the system clipboard, if a clipboard tool is found (pbcopy/wl-copy/xclip/xsel); local only, silent no-op over ssh |
| mouse drag | N | visual selection (\`mouse=a\`); \`ttymouse=sgr\` for wide terminals and drag-vs-move |
| PageUp/PageDown | N/I/V | vim's own paging — deliberately **not** remapped |

## Buffers

vim defaults; no custom buffer mappings exist yet.

| Command | Does |
| ------- | ---- |
| \`:e {file}\` | edit/open a file in the current window |
| \`:bn\` / \`:bp\` | next / previous buffer |
| \`:b {N\|name}\` | jump to buffer by number or name |
| \`:ls\` / \`:buffers\` | list open buffers |
| \`:bd\` | delete (close) current buffer |
| \`:bd {N}\` | delete buffer N |
| \`Ctrl-^\` | toggle to the alternate (previously edited) buffer |
| \`:w\` | write current buffer |
| \`:wa\` | write all changed buffers |
| \`:q\` / \`:q!\` | close window / discard changes and close |
| \`:x\` / \`ZZ\` | write if changed, then close |
| \`:qa\` / \`:qa!\` | close all windows / discard all and quit |

## Windows and splits

vim defaults, all under the \`Ctrl-w\` prefix. \`<M-h/j/k/l>\` and \`<M-H/J/K/L>\` above are the
custom fast path for focus/resize; everything else here is unmapped default vim.

| Command | Does |
| ------- | ---- |
| \`:sp\` / \`Ctrl-w s\` | horizontal split |
| \`:vs\` / \`Ctrl-w v\` | vertical split |
| \`Ctrl-w w\` | cycle to next window |
| \`Ctrl-w h/j/k/l\` | move focus left/down/up/right |
| \`Ctrl-w H/J/K/L\` | move the window itself to the far left/bottom/top/right |
| \`Ctrl-w =\` | equalize all window sizes |
| \`Ctrl-w +/-\` | grow/shrink height |
| \`Ctrl-w </>\` | shrink/grow width |
| \`Ctrl-w \_\` / \`Ctrl-w \|\` | maximize height / width |
| \`Ctrl-w o\` | close all windows but this one |
| \`Ctrl-w q\` / \`:close\` | close this window |
| \`Ctrl-w T\` | move window into its own tab |
| \`:tabnew\`, \`gt\`, \`gT\` | new tab, next tab, previous tab |

## Panes (tmux, hosting vim)

Not vim itself, but the layer vim splits live inside. Full table in
\`scripts/keyboard/CHEATSHEET.md\`; the ones that matter alongside vim:

| Key | Does |
| --- | ---- |
| \`Alt-\\\` | split tmux pane vertical |
| \`Alt--\` | split tmux pane horizontal |
| \`Alt-z\` | zoom/unzoom current pane |
| \`Alt-w\` | kill current pane |
| \`Alt-Tab\` / \`Alt-Shift-Tab\` | cycle panes, next/previous — **never** forwarded into vim, the guaranteed way out if focus ever gets stuck |
| \`Alt-h/j/k/l\`, \`Alt-H/J/K/L\` | forwarded into vim when the pane runs vim (see above); otherwise move/resize the tmux pane directly |

## Cursor movement — Normal mode

| Key | Does |
| --- | ---- |
| \`h j k l\` | left / down / up / right |
| \`w\` / \`b\` / \`e\` | next word start / previous word start / word end |
| \`0\` / \`^\` / \`\$\` | start of line / first non-blank / end of line |
| \`gg\` / \`G\` | first line / last line |
| \`{N}G\` or \`:{N}\` | go to line N |
| \`{\` / \`}\` | previous / next paragraph |
| \`%\` | jump to matching bracket |
| \`Ctrl-u\` **(remapped here)** | vim default: half-page up. In this config, \`Ctrl-Up\` does this instead |
| \`Ctrl-d\` **(remapped here)** | vim default: half-page down. In this config, \`Ctrl-Down\` does this instead |
| \`Ctrl-f\` / \`Ctrl-b\` | full page down / up |
| \`H\` / \`M\` / \`L\` | top / middle / bottom of window |
| \`*\` / \`#\` | next / previous occurrence of word under cursor |
| \`f{c}\` / \`F{c}\` | jump to next/previous occurrence of char \`c\` on the line |
| \`t{c}\` / \`T{c}\` | jump to just before next/previous occurrence of char \`c\` |
| \`m{a}\` | set mark \`a\` |
| two backticks + \`{a}\`, or \`'{a}\` | jump to mark \`a\` (exact position / start of line) |

## Editing — Normal mode

| Key | Does |
| --- | ---- |
| \`i\` / \`a\` | insert before / after cursor |
| \`I\` / \`A\` | insert at start / end of line |
| \`o\` / \`O\` | open new line below / above, enter insert mode |
| \`x\` / \`X\` | delete char forward / backward |
| \`dd\` | delete (cut) line |
| \`dw\`, \`de\`, \`d\$\`, \`d0\` | delete to next word / word end / end of line / start of line |
| \`cc\` / \`cw\` | change line / change word (delete + insert) |
| \`yy\` | yank (copy) line — **also copies to system clipboard here** |
| \`p\` / \`P\` | paste after / before cursor |
| \`u\` / \`Ctrl-r\` | undo / redo |
| \`.\` | repeat last change |
| \`r{c}\` | replace char under cursor with \`c\` |
| \`~\` | toggle case of char under cursor |
| \`>>\` / \`<<\` | indent / outdent line |
| \`{N}{cmd}\` | prefix any of the above with a count, e.g. \`3dd\` deletes 3 lines |
| \`v\` / \`V\` / \`Ctrl-v\` | start visual / visual-line / visual-block selection |
| \`:s/pat/rep/\` | substitute on current line; add \`g\` for all matches, \`%\` before \`s\` for whole file |

## Editing — Insert mode

| Key | Does |
| --- | ---- |
| \`Esc\` | back to Normal mode |
| arrow keys | move cursor (breaks the insert "undo chunk") |
| \`Ctrl-Up\` / \`Ctrl-Down\` **(this config)** | half-page scroll, same as Normal mode |
| \`Ctrl-a\` / \`Ctrl-e\` **(this config)** | jump to start / end of line, same as \`Home\`/\`End\` |
| \`Ctrl-w\` | delete word before cursor |
| \`Ctrl-u\` | delete to start of line |
| \`Ctrl-t\` / \`Ctrl-d\` | indent / outdent current line |
| \`Ctrl-o\` | run one Normal-mode command, then return to Insert |
| \`Ctrl-r {reg}\` | insert contents of register \`reg\` (e.g. \`Ctrl-r "\` for last yank/delete) |
| \`Ctrl-n\` / \`Ctrl-p\` | next / previous keyword completion match |
| \`Ctrl-v {code}\` | insert a literal character by code |
| paste (\`Cmd-V\`/\`Super-V\`) | bracketed paste — no auto-indent staircase, no mapping needed |

## Command-line mode (\`:\`, \`/\`, \`?\`)

| Key | Does |
| --- | ---- |
| \`:\` | enter command-line mode |
| \`/pattern\`, \`?pattern\` | search forward / backward |
| \`n\` / \`N\` | repeat last search, same / opposite direction |
| \`Ctrl-a\` / \`Ctrl-e\` | start / end of the command line (vim default here, unaffected by the Normal/Insert remap above) |
| \`Tab\` | complete command/filename |
| Up / Down or \`Ctrl-p\` / \`Ctrl-n\` | previous / next command-line history entry |
EOF

echo "wrote $OUT"
