#!/bin/sh
#
# Terminal-emulator half of the keyboard standard on Linux.  See ../README.md.
#
# The terminal emulator owns Cmd/Super, because Cmd/Super has no byte encoding and so
# can never reach tmux or vim.  iTerm2 already binds Cmd-C/V/T/W and Cmd-1..9 natively,
# so macOS needs nothing here -- this file exists to move Linux terminals onto Super so
# the two match.
#
#   Super-C / Super-V   copy / paste
#   Super-T / Super-W   new tab / close tab
#   Super-N             new window
#   Super-1 .. Super-9  tab N
#   Super-Left/Right    prev / next tab
#   Super-Tab           switch application  (the OS, not the terminal -- matches Cmd-Tab)
#
# Alt is left completely alone here: it belongs to tmux and vim.
#
# Idempotent.  Self-guarding: each block no-ops when its terminal is not installed.

set -e

# --------------------------------------------------------------------------------------
# GNOME Shell first: it holds Super-1..9 for the dash, which would swallow the tab keys.
# --------------------------------------------------------------------------------------
if which gsettings >/dev/null 2>&1 \
   && gsettings list-schemas 2>/dev/null | grep -q '^org\.gnome\.shell\.keybindings$'; then
  i=1
  while [ $i -le 9 ]; do
    gsettings set org.gnome.shell.keybindings "switch-to-application-${i}" "[]"
    i=$((i + 1))
  done
  echo "keyboard: released Super-1..9 from the GNOME dash"
fi

# --------------------------------------------------------------------------------------
# Alt-Tab belongs to the terminal, not the window manager.
#
# GNOME ships switch-applications bound to BOTH <Super>Tab and <Alt>Tab, so the same
# gesture is on two modifiers and the Alt one shadows tmux's pane cycling before the
# terminal ever sees the keystroke.  Pinning it to Super-Tab alone does two things at
# once: it matches macOS, where Cmd-Tab is the application switcher and Option-Tab is
# free, and it frees Alt-Tab to reach tmux -- which is the modifier rule this whole
# standard runs on (Super = OS and terminal emulator, Alt = inside the terminal).
#
# Same treatment for the backward pair, or Alt-Shift-Tab would still be caught here while
# Alt-Tab passed through, which is worse than either consistent outcome.
# --------------------------------------------------------------------------------------
if which gsettings >/dev/null 2>&1 \
   && gsettings list-schemas 2>/dev/null | grep -q '^org\.gnome\.desktop\.wm\.keybindings$'; then
  gsettings set org.gnome.desktop.wm.keybindings switch-applications \
    "['<Super>Tab']"
  gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward \
    "['<Shift><Super>Tab']"
  echo "keyboard: Alt-Tab released to tmux; app switching is Super-Tab"
fi

# --------------------------------------------------------------------------------------
# gnome-terminal.  Relocatable schema, so the path suffix is mandatory.
# --------------------------------------------------------------------------------------
if which gnome-terminal >/dev/null 2>&1 && which gsettings >/dev/null 2>&1; then
  GT="org.gnome.Terminal.Legacy.Keybindings:/org/gnome/terminal/legacy/keybindings/"

  gsettings set "$GT" copy       "'<Super>c'"
  gsettings set "$GT" paste      "'<Super>v'"
  gsettings set "$GT" select-all "'<Super>a'"
  gsettings set "$GT" find       "'<Super>f'"
  gsettings set "$GT" new-tab    "'<Super>t'"
  gsettings set "$GT" close-tab  "'<Super>w'"
  gsettings set "$GT" new-window "'<Super>n'"
  gsettings set "$GT" prev-tab   "'<Super>Left'"
  gsettings set "$GT" next-tab   "'<Super>Right'"

  # switch-to-tab-N ships bound to <Alt>N, which would collide head-on with the tmux
  # window keys.  Moving them to Super is what frees Alt for tmux.
  i=1
  while [ $i -le 9 ]; do
    gsettings set "$GT" "switch-to-tab-${i}" "'<Super>${i}'"
    i=$((i + 1))
  done
  # Beyond 9 there is no Super key to use; unbind rather than leave them on Alt.
  i=10
  while [ $i -le 20 ]; do
    gsettings set "$GT" "switch-to-tab-${i}" "'disabled'" 2>/dev/null || true
    i=$((i + 1))
  done

  gsettings set org.gnome.Terminal.Legacy.Settings menu-accelerator-enabled false
  echo "keyboard: gnome-terminal moved to Super; Alt released to tmux"
fi

# --------------------------------------------------------------------------------------
# foot.  Config file rather than gsettings; only the keybind sections are rewritten.
# --------------------------------------------------------------------------------------
if which foot >/dev/null 2>&1; then
  FOOT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/foot"
  mkdir -p "${FOOT_DIR}"
  cat > "${FOOT_DIR}/keyboard.ini" <<'EOF'
# Generated by dotfiles .keyboard/linux/terminal.sh -- edits here are overwritten.
# Include this from foot.ini with:  include=~/.config/foot/keyboard.ini

[key-bindings]
clipboard-copy=Super+c
clipboard-paste=Super+v
search-start=Super+f
font-increase=Super+plus
font-decrease=Super+minus
font-reset=Super+0

[search-bindings]
find-prev=Super+Shift+g
find-next=Super+g
EOF

  # foot has no include-by-default, so wire it up once without clobbering existing config.
  if [ ! -f "${FOOT_DIR}/foot.ini" ]; then
    printf 'include=%s/keyboard.ini\n' "${FOOT_DIR}" > "${FOOT_DIR}/foot.ini"
  elif ! grep -q 'keyboard\.ini' "${FOOT_DIR}/foot.ini"; then
    printf '\ninclude=%s/keyboard.ini\n' "${FOOT_DIR}" >> "${FOOT_DIR}/foot.ini"
  fi
  echo "keyboard: foot moved to Super"
fi

# foot has no tab concept and xterm has no configurable shortcuts at all; both are
# reachable through tmux, which is the point of putting the frequent operations there.
