#!/bin/sh
#
# Terminal-emulator half of the keyboard standard on Linux.  See docs/keyboard.md.
#
# Applies the GNOME side of scripts/keyboard/keys.yaml: GNOME Shell releases (so Super-1..9,
# Super-A/N/V and Alt-Tab reach the terminal) and the gnome-terminal Super shortcuts.  The
# settings themselves are in gnome-keys.sh, GENERATED by scripts/keyboard/render.sh; this
# file only applies them.
#
# kitty needs nothing here: it reads .config/kitty/keys.conf, linked into place with the
# rest of its directory.  iTerm2 binds Cmd natively on macOS.
#
# Idempotent.  gsettings changes the live session, so it only runs against the real home.

set -e
: "${SCRIPT_DIR:=$(CDPATH= cd -- "$(dirname -- "$0")/../../.." && pwd)}"
TARGET=${1:-${TARGET:-$HOME}}
MODULE=keyboard
. "${SCRIPT_DIR}/scripts/lib.sh"

GNOME_KEYS="${SCRIPT_DIR}/scripts/keyboard/linux/gnome-keys.sh"

if ! live_home || ! have gsettings; then
  log "no live gsettings session; GNOME key settings skipped"
  exit 0
fi

# Schemas present on this machine, fixed and relocatable.  A schema that is absent (no
# GNOME Shell, no gnome-terminal) is skipped silently rather than failing the whole run.
SCHEMAS=$( { gsettings list-schemas; gsettings list-relocatable-schemas; } 2>/dev/null)
applied=0
skipped=0
failed=0

# gset SCHEMA[:PATH] KEY VALUE -- called once per line of gnome-keys.sh.
gset() {
  if ! printf '%s\n' "${SCHEMAS}" | grep -qxF "${1%%:*}"; then
    skipped=$((skipped + 1))
    return 0
  fi
  if gsettings set "$1" "$2" "$3" 2>/dev/null; then
    applied=$((applied + 1))
  else
    failed=$((failed + 1))     # e.g. switch-to-tab-N beyond what this version defines
  fi
}

. "${GNOME_KEYS}"

log "gsettings: ${applied} applied, ${skipped} skipped (schema absent), ${failed} not supported here"
